ADORO_MVC/Controllers/SalasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ADORO_MVC.Context;
using ADORO_MVC.Models;

namespace ADORO_MVC.Controllers
{
    public class SalasController : Controller
    {
        private readonly AdoroDatabaseContext _context;

        public SalasController(AdoroDatabaseContext context)
        {
            _context = context;
        }

        // GET: Salas
        public async Task<IActionResult> Index()
        {
            return View(await _context.Salas.ToListAsync());
        }

        // GET: Salas/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var sala = await _context.Salas
                .FirstOrDefaultAsync(m => m.Id == id);
            if (sala == null)
            {
                return NotFound();
            }

            return View(sala);
        }

        // GET: Salas/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Salas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nombre,CapacidadMax,AlAireLibre")] Sala sala)
        {
            if (ModelState.IsValid)
            {
                if(sala.CapacidadMax <= 0)
                {
                    ViewBag.mensajeError = "La capacidad maxima debe ser mayor a 0.";
                    return View();
                }
                _context.Add(sala);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(sala);
        }

        // GET: Salas/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var sala = await _context.Salas.FindAsync(id);
            if (sala == null)
            {
                return NotFound();
            }
            return View(sala);
        }

        // POST: Salas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nombre,CapacidadMax,AlAireLibre")] Sala sala)
        {
            if (id != sala.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var ActividadesDeSalas = _context.Actividades
                    .Where(f => f.SalaId == id)
                    .ToList();
                    foreach (var actividad in ActividadesDeSalas)
                    {
                        if(actividad.Contador > sala.CapacidadMax)
                        {
                            ViewBag.mensajeError = "Hay una actividad en dicha sala con una cantidad de participantes mayor a la capacidad maxima seleccionada.";
                            return View();
                        }
                    }
                    if (sala.CapacidadMax <= 0)
                    {
                        ViewBag.mensajeError = "La capacidad maxima debe ser mayor a 0.";
                        return View();
                    }
                    _context.Update(sala);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SalaExists(sala.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(sala);
        }

        // GET: Salas/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var sala = await _context.Salas
                .FirstOrDefaultAsync(m => m.Id == id);
            if (sala == null)
            {
                return NotFound();
            }

            return View(sala);
        }

        // POST: Salas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var sala = await _context.Salas.FindAsync(id);
            var ActividadesDeSalas = _context.Actividades
                .Where(f => f.SalaId==id)
                .ToList();
            if (!ActividadesDeSalas.Any()) //avisa que no la borró? https://www.c-sharpcorner.com/UploadFile/dacca2/various-return-types-from-mvc-controller/

            {
                _context.Salas.Remove(sala);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            else
            {
                ViewBag.mensajeError = "No se puede eliminar la sala porque tiene actividades asociadas";
                return View("Delete", sala);
            }
        }

        private bool SalaExists(int id)
        {
            return _context.Salas.Any(e => e.Id == id);
        }
    }
}

ADORO_MVC/Controllers/UsuariosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ADORO_MVC.Context;
using ADORO_MVC.Models;
using Microsoft.AspNetCore.Http;
using System.Text.RegularExpressions;

namespace ADORO_MVC.Controllers
{
    public class UsuariosController : Controller
    {
        private readonly AdoroDatabaseContext _context;

        public UsuariosController(AdoroDatabaseContext context)
        {
            _context = context;
        }

        // GET: Usuarios
        public async Task<IActionResult> Index()
        {
            return View(await _context.Usuario.ToListAsync());
        }

        // GET: Usuarios/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var usuario = await _context.Usuario
                .FirstOrDefaultAsync(m => m.Id == id);
            if (usuario == null)
            {
                return NotFound();
            }

            return View(usuario);
        }

        // GET: Usuarios/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Usuarios/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nombre,Apellido,UserName,Password,Rol")] Usuario usuario)
        {
            if (ModelState.IsValid)
            {
                _context.Add(usuario);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(usuario);
        }

        // GET: Usuarios/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var usuario = await _context.Usuario.FindAsync(id);
            if (usuario == null)
            {
                return NotFound();
            }
            return View(usuario);
        }

        // POST: Usuarios/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nombre,Apellido,UserName,Password,Rol")] Usuario usuario)
        {
            if (id != usuario.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(usuario);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UsuarioExists(usuario.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(usuario);
        }

        // GET: Usuarios/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var usuario = await _context.Usuario
                .FirstOrDefaultAsync(m => m.Id == id);
            if (usuario == null)
            {
                return NotFound();
            }

            return View(usuario);
        }

        // POST: Usuarios/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var usuario = await _context.Usuario.FindAsync(id);
            _context.Usuario.Remove(usuario);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool UsuarioExists(int id)
        {
            return _context.Usuario.Any(e => e.Id == id);
        }

        public IActionResult Register()
        {
            return View();
        }

        // POST: Usuarios/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Register([Bind("Id,Nombre,Apellido,UserName,Password")] Usuario usuario)
        {
            if (ModelState.IsValid)
            {
                var usuarioEncontrado = await _context.Usuario.FirstOrDefaultAsync(m => m.UserName == usuario.UserName);
                if (usuarioEncontrado != null)
                {
                    ViewBag.mensajeError = "El nombre de usuario ya existe.";
                    return View();
                }
                else if (!Regex.IsMatch(usuario.Nombre, @"^[a-zA-Z]+$"))
                {
                    ViewBag.mensajeError = "El nombre debe contener sólo caracteres alfabéticos.";
                    return View();
                }
                else if (!Regex.IsMatch(usuario.Apellido, @"^[a-zA-Z]+$"))
                {
                    ViewBag.mensajeError = "El apellido debe contener sólo caracteres alfabéticos.";
                    return View();
                }
                else if (!Regex.IsMatch(usuario.Password, @"^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&.])[A-Za-z\d@$!%*?&.]{8,}$"))
                {
                    ViewBag.mensajeError = "La contraeña debe contener al menos 8 digitos, una letra mayúscula, una minúscula, un número y alguno de los siguientes símbolos: @$!%*?&.";
                    return View();
                }
                usuario.Rol = Rol.User;
                _context.Add(usuario);
                await _context.SaveChangesAsync();
                return View("Login");
            }
            return View();
        }

        public IActionResult Login()
        {
            return View();
        }

        // POST: Usuarios/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Login([Bind("UserName,Password")] Usuario usuario)
        {
            if (ModelState.IsValid)
            {
                var usuarioEncontrado = await _context.Usuario.FirstOrDefaultAsync(m => m.UserName == usuario.UserName && m.Password == usuario.Password);
                if (usuarioEncontrado == null)
                {
                    ViewBag.mensajeError = "Los datos ingresados son incorrectos.";
                    return View();
                }
                else
                {
                    HttpContext.Session.SetString("Rol", usuarioEncontrado.Rol.ToString());
                    HttpContext.Session.SetString("UserName", usuarioEncontrado.UserName);
                    return View("~/Views/Home/Index.cshtml", await _context.Actividades.ToListAsync());
                }
            }
            return View();
        }

        public async Task<IActionResult> Logout()
        {
            HttpContext.Session.SetString("Rol", "");
            HttpContext.Session.SetString("UserName", "");
            return View("~/Views/Home/Index.cshtml", await _context.Actividades.ToListAsync());
        }


        //Desde aca intentando el login
        // GET: Usuarios/LogIn
        //public async Task<IActionResult> Login()
        //{

        //    Me parece que tendria que ir a una vista de login
        //    con un recuadro para el username
        //    uno para la pass
        //    Al hacer click en login debería ir a POST de login
        //    return View(Login);
        //}

        // POST: Usuarios/Login
        //[HttpPost, ActionName("Login")]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> Login2()
        //{
        //    //Hay que buscar en la tabla por username, no por ID, no?
        //    //Si coinciden los datos hay que HttpContext.Session.SetString("usuario", usuario);
        //    return View(LogIn);
        //}
        //public ActionResult SendEmail()
        //{
        //    return View();
        //}
        //[HttpPost]
        //public ActionResult SendEmail(string receiver, string subject, string message)
        //{
        //    try
        //    {
        //        if (ModelState.IsValid)
        //        {
        //            var senderEmail = new MailAddress("lognml@gmail.com", "Jamil");
        //            var receiverEmail = new MailAddress(receiver, "Receiver");
        //            var password = "Your Email Password here";
        //            var sub = subject;
        //            var body = message;
        //            var smtp = new SmtpClient
        //            {
        //                Host = "smtp.gmail.com",
        //                Port = 587,
        //                EnableSsl = true,
        //                DeliveryMethod = SmtpDeliveryMethod.Network,
        //                UseDefaultCredentials = false,
        //                Credentials = new NetworkCredential(senderEmail.Address, password)
        //            };
        //            using (var mess = new MailMessage(senderEmail, receiverEmail)
        //            {
        //                Subject = subject,

ADORO_MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ADORO</title> @*//Saqué _MVC*@
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Josefin+Sans:wght@500&display=swap" rel="stylesheet">
    @using Microsoft.AspNetCore.Http;
    <style>
        .contenedor {
            overflow: hidden;
            background-color: #333;
            top: 0;
            width: 100%;
            background: #ffa900;
        }
    </style>
</head>
<body>
    <header>
        @* navbar-light bg-white border-bottom box-shadow mb-3*@
        <nav class="contenedor navbar navbr-default navbar-expand-sm navbar-toggleable-sm navbar-fixed-top">
            <div class="container-menu">
                <table>
                    <tr>
                        <td>
                            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ADORO</a> @*//Saqué _MVC*@
                            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                                    aria-expanded="false" aria-label="Toggle navigation">
                                <span class="navbar-toggler-icon"></span>
                            </button>
                        </td>



                        <td>
                            <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                                <ul class="navbar-nav flex-grow-1">

                                    @if (Context.Session.GetString("Rol") == "Admin")
                                    {
                                        <li class="nav-item">
                                            <a class="nav-link text-dark" asp-area="" asp-controller="Salas" asp-action="Index">Salas</a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link text-dark" asp-area="" asp-controller="Actividades" asp-action="Index">Actividades</a>
                                        </li>

                                        <li class="nav-item">
                                            <a class="nav-link text-dark" asp-area="" asp-controller="Usuarios" asp-action="Index">Usuarios</a>
                                        </li>
                                    }
                                  
                                      @if (Context.Session.GetString("Rol") != "Admin" && Context.Session.GetString("Rol") != "User")
                                        {
                                            <li class="nav-item">
                                                <a class="nav-link text-dark" asp-area="" asp-controller="Usuarios" asp-action="Login">Ingresar</a>
                                            </li>
                                            <li class="nav-item">
                                                <a class="nav-link text-dark" asp-area="" asp-controller="Usuarios" asp-action="Register">Registrarse</a>
                                            </li>
                                        }
                                        else
                                        {
                                            <li class="nav-item">
                                                <a class="nav-link text-dark" asp-area="" asp-controller="Usuarios" asp-action="Logout">@Context.Session.GetString("UserName") - Cerrar Sesion</a>
                                            </li>
                                        }
                                    </ul>
</div>
                        </td>
                    </tr>
                </table>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="contenedor-2 container">
            &copy; 2022 - ADORO
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

@*Cómo se genera más espacio lateral acá?
    Que solo muestre Ingresar.
    Que dentro de Ingresar haya un "registrarse"
    Que si ya estás login diga SALIR
    La vista de create user en todo caso podría ser para Registrarse
    usr=HttpContext.Session.GetString("usuario");
    if(usr=null) {que se vea Ingresar} else {que se vea Salir] *@